import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { GeistSans } from "geist/font/sans";

import "./globals.css";

const nunito_font = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${GeistSans.variable} ${nunito_font} "font-sans h-full bg-background text-foreground" `}
      >
        {children}
      </body>
    </html>
  );
}
